site:
  title: Upgrade a RHOSP 17.1 to RHOSO 18 using the adoption mechanism
  start_page: REPLACEREPONAME::index.adoc

content:
  sources:
  - url: ./
    branches: HEAD

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
